CREATE DATABASE IF NOT EXISTS shah_writes;
USE shah_writes;

CREATE TABLE IF NOT EXISTS books (
  id VARCHAR(64) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  rating INT NOT NULL,
  category VARCHAR(120) NOT NULL,
  cover TEXT NOT NULL,
  pdf TEXT NOT NULL,
  description TEXT NOT NULL,
  hidden TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
